name: AK Photography
favicon: null
layout_spectrum: 0.75047
typography_spectrum: 0.2533
title: Andy Kulis Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
