layout_spectrum: 0.6324087709654123
typography_spectrum: 0.24054865958169103
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.10208298498764634
  lightness: 0.5920038556214422
  saturation: 0.7022520666942
  rhythmicContrast: 0.5498835758771747
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Andy Kulis Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: andy kulis photos
purpose: []
