typography_spectrum: 0.129
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24765
analytics:
  google: null
  facebook: null
  twitter: null
name: Andy Kulis Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: andy kulis photos
purpose: []
