layout_spectrum: 0.29395167938728656
typography_spectrum: 0.1762192721260103
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.7415112514201884
  lightness: 0.746632358956123
  saturation: 0.7766028322452808
  rhythmicContrast: 0.31128448870042247
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: andy kulis photography
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: yo
    id: 68cbb8e8-eedb-4ee5-bf10-781b971fceb5
    type: content
  - name: Landscapes
    id: 48aad20d-76d3-474a-83b4-1995e8bd207a
    type: content
  - name: About Me
    id: 8e5d6db3-9ea2-4d82-8dcc-9e1d0f92a321
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c03c9aa7-e70d-4fdd-bdc8-6f30cf8650da.png
title: andy kulis photos
content: []
description: i freeze time
purpose: []
