typography_spectrum: 0.24054865958169103
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.10208298498764634
  lightness: 0.5920038556214422
  saturation: 0.7022520666942
  rhythmicContrast: 0.5498835758771747
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6324087709654123
analytics:
  google: null
  facebook: null
  twitter: null
name: Andy Kulis Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/10d39987-d63f-4026-b977-ff637b55f770.png
title: andy kulis photos
purpose: []
